data_folder = '../finished_files/chunked'
vocab_file = '../finished_files/vocab'
bleurt_model = '../bleurt/bleurt/test_checkpoint'
checkpoints_folder = './chk'
experiment_name = 'rl_testing'
load_model_path = None
vocab_size = 50000
article_max_tokens = 400
summary_max_tokens = 120
pretrain_epochs = 15
rl_train_epochs = 10
cover_loss_iters = 2000
batch_size = 5
gpu_ids = [0, 1, 2, 3, 4]
